### ISSUE TITLE
Key lstm_o/rnn/basic_lstm_cell/kernel not found in checkpoint

### ISSUE THREAD

**Issue by senliuy** [eragonruan/text-detection-ctpn#1]
Dear eragonruan,
I think your implementation of ctpn is an excellent job. When I run your demo, I have loaded other layers successfully except the lstm layer, It shows the output following:
`Loading network VGGnet_test... 
Traceback (most recent call last):
  File "ctpn/demo.py", line 89, in <module>
    saver.restore(sess, os.path.join(os.getcwd(),"checkpoints/model_final.ckpt"))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key lstm_o/rnn/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_28 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_28/tensor_names, save/RestoreV2_28/shape_and_slices)]]

Caused by op u'save/RestoreV2_28', defined at:
  File "ctpn/demo.py", line 88, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key lstm_o/rnn/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_28 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_28/tensor_names, save/RestoreV2_28/shape_and_slices)]]`

Could you please tell me where I'm wrong? The version of TensorFlow that I am using is 1.3

**Comment by justttry** [comment]
i have the same problem.

**Comment by eragonruan** [comment]
@senliuy  @justttry I think this bug is caused by different version of tensorflow. My version is 1.1.0. here is a related problem,see this [link](https://github.com/KranthiGV/Pretrained-Show-and-Tell-model/issues/7)

**Comment by justttry** [comment]
@eragonruan 
yes, i solve the problem. thank you.
below is the converting code.

#####################################################
#encoding:UTF-8

path = "YOUR/CHECKPOINT/PATH"
OLD_CHECKPOINT_FILE = path + "model_final.ckpt"
NEW_CHECKPOINT_FILE = path + "model2_final.ckpt"

import tensorflow as tf
vars_to_rename = {
    "lstm_o/rnn/basic_lstm_cell/weights": "lstm_o/rnn/basic_lstm_cell/kernel",
    "lstm_o/rnn/basic_lstm_cell/biases" : "lstm_o/rnn/basic_lstm_cell/bias",
}
new_checkpoint_vars = {}
reader = tf.train.NewCheckpointReader(OLD_CHECKPOINT_FILE)
for old_name in reader.get_variable_to_shape_map():
    print old_name
    if old_name in vars_to_rename:
        new_name = vars_to_rename[old_name]
    else:
        new_name = old_name
    new_checkpoint_vars[new_name] = tf.Variable(reader.get_tensor(old_name))

init = tf.global_variables_initializer()
saver = tf.train.Saver(new_checkpoint_vars)

with tf.Session() as sess:
    sess.run(init)
    saver.save(sess, NEW_CHECKPOINT_FILE)

**Comment by sahithikilaru** [comment]
What are we supposed to write instead of "YOUR/CHECKPOINT/PATH"?

**Comment by sahithikilaru** [comment]
ALso, the line 'print old_name' gives an error

**Comment by eragonruan** [comment]
@sahithikilaru the checkpoints provided is in [here](https://github.com/eragonruan/text-detection-ctpn/tree/master/checkpoints)
print(old_name)
