### ISSUE TITLE
[Questtion] cannot import name 'bbox'

### ISSUE THREAD

**Issue by hoangtocdo90** [eragonruan/text-detection-ctpn#105]
Hi guys please help me.
I'm run setup.py sucessfull and move bbox.o ,cython_nms.o to until folder. 
I'm using python 3.6 , tensorflow 1.6 and native pip not using conda. What's wrong whith me ?
thanks
`usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "ctpn/demo.py", line 8, in <module>
    from lib.networks.factory import get_network
  File "/notebooks/text-detection-ctpn/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/notebooks/text-detection-ctpn/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import train
  File "/notebooks/text-detection-ctpn/lib/fast_rcnn/train.py", line 5, in <module>    from ..roi_data_layer.layer import RoIDataLayer
  File "/notebooks/text-detection-ctpn/lib/roi_data_layer/__init__.py", line 1, in <module>
    from . import roidb
  File "/notebooks/text-detection-ctpn/lib/roi_data_layer/roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "/notebooks/text-detection-ctpn/lib/utils/__init__.py", line 4, in <module>
    from . import bbox
ImportError: cannot import name 'bbox'
root@1eb36290c8ad:/notebooks/text-detection-ctpn# ^C
root@1eb36290c8ad:/notebooks/text-detection-ctpn# ^C
root@1eb36290c8ad:/notebooks/text-detection-ctpn#`

**Comment by FantDing** [comment]
Read the `README.md` and run 
```bash
cd lib/utils
chmod +x make.sh
./make.sh
```
