### ISSUE TITLE
kernel not found in checkpoint

### ISSUE THREAD

**Issue by hsddlz** [eragonruan/text-detection-ctpn#11]
hi,I got this problem....
Loading network VGGnet_test... 
Traceback (most recent call last):
  File "./ctpn/demo.py", line 90, in <module>
    saver.restore(sess, os.path.join(os.getcwd(),"checkpoints/model_final.ckpt"))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key lstm_o/rnn/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_28 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_28/tensor_names, save/RestoreV2_28/shape_and_slices)]]

Caused by op u'save/RestoreV2_28', defined at:
  File "./ctpn/demo.py", line 89, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key lstm_o/rnn/basic_lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_28 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_28/tensor_names, save/RestoreV2_28/shape_and_slices)]]

so I search net and found this [Issue](https://github.com/KranthiGV/Pretrained-Show-and-Tell-model/issues/7)
I change u demo code like this:

if __name__ == '__main__':
    if os.path.exists("data/results/"):   
        shutil.rmtree("data/results/")	  
    os.makedirs("data/results/")	  

    cfg.TEST.HAS_RPN = True  # Use RPN for proposals
    # init session
    config = tf.ConfigProto(allow_soft_placement=True)
    sess = tf.Session(config=config)
    # load network
    net = get_network("VGGnet_test")
    # load model
    print ('Loading network {:s}... '.format("VGGnet_test")),
## I changed this part
    OLD_CHECKPOINT_FILE = "checkpoints/model_final.ckpt"
    #NEW_CHECKPOINT_FILE = "model_final.ckpt"  
    vars_to_rename = {
        "lstm/basic_lstm_cell/weights": "lstm/basic_lstm_cell/kernel",
        "lstm/basic_lstm_cell/biases": "lstm/basic_lstm_cell/bias",
    }
    new_checkpoint_vars = {}
    reader = tf.train.NewCheckpointReader(OLD_CHECKPOINT_FILE)
    for old_name in reader.get_variable_to_shape_map():
        if old_name in vars_to_rename:
	    new_name = vars_to_rename[old_name]
        else:
	    new_name = old_name
        new_checkpoint_vars[new_name] = tf.Variable(reader.get_tensor(old_name))

    saver = tf.train.Saver(new_checkpoint_vars)
    init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(init)
        saver.restore(sess, os.path.join(os.getcwd(),"checkpoints/model_final.ckpt"))
        print 'done'
        im = 128 * np.ones((300, 300, 3), dtype=np.uint8)
        for i in xrange(2):
            _, _ = test_ctpn(sess, net, im)
        im_names = glob.glob(os.path.join(cfg.DATA_DIR, 'demo', '*.png')) + \
	           glob.glob(os.path.join(cfg.DATA_DIR, 'demo', '*.jpg'))
        for im_name in im_names:
	    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
	    #print('Demo for {:s}'.format(im_name))
	    ctpn(sess, net, im_name)
It was already run , but in ctpn line is empty .I thought threshold may  a little high that I make it lower.
so the bounding box didn't find right proposal.

btw can u speak chinese`````:)

**Comment by eragonruan** [comment]
see this two issues: [issue#1](https://github.com/eragonruan/text-detection-ctpn/issues/1) 、[issue#2](https://github.com/eragonruan/text-detection-ctpn/issues/2). in checkpoints, I provided two model, one for tf1.1 and one for tf1.3.
If this problem still occurs, feel free to contact
