### ISSUE TITLE
report the flowing error( KeyError: 'max_overlaps') while training my own dataset(contain about 10000 photos) 

### ISSUE THREAD

**Issue by Fourmiiy** [eragonruan/text-detection-ctpn#128]
Traceback (most recent call last):
  File "ctpn/train_net.py", line 36, in <module>
    restore=bool(int(cfg.TRAIN.restore)))
  File "/home/chendali1/gaoshengjun/text-detection-ctpn-master/lib/fast_rcnn/train.py", line 232, in train_net
    sw = SolverWrapper(sess,network, imdb, roidb, output_dir,log_dir, pretrained_model=pretrained_model)
  File "/home/chendali1/gaoshengjun/text-detection-ctpn-master/lib/fast_rcnn/train.py", line 26, in __init__
    self.bbox_means, self.bbox_stds = rdl_roidb.add_bbox_regression_targets(roidb)
  File "/home/chendali1/gaoshengjun/text-detection-ctpn-master/lib/roi_data_layer/roidb.py", line 56, in add_bbox_regression_targets
    max_overlaps = roidb[im_i]['max_overlaps']

**Comment by Fourmiiy** [comment]
I delete the file cache ,but it doesn't work , could anyone help me ? thanks

**Comment by czh0001** [comment]
meet the same problem......

**Comment by czh0001** [comment]
Only these days I met this problem

**Comment by czh0001** [comment]
I meet the same problem......Only these days I met this problem.I did not meet this problem one or two months ago.Seeking for help...

**Comment by czh0001** [comment]
delete the foler text-detection-ctpn/data/cache may helps.

**Comment by SophieSongSong** [comment]
delete the foler text-detection-ctpn/data/cache works for me. thanks!
