### ISSUE TITLE
how can i deal with it ?

### ISSUE THREAD

**Issue by fooooooooox** [eragonruan/text-detection-ctpn#129]
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
hust@hust-X299-AORUS-Gaming-7:~/ocr/text-detection-ctpn-master/text-detection-ctpn-master/ctpn$ source activate ocr
(ocr) hust@hust-X299-AORUS-Gaming-7:~/ocr/text-detection-ctpn-master/text-detection-ctpn-master/ctpn$ python demo.py 
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from lib.networks.factory import get_network
ImportError: No module named lib.networks.factory

**Comment by eragonruan** [comment]
@fooooooooox try using python3

**Comment by Mary2333** [comment]
Hi, my python is 2.7, I also met the issue, I think you should install tensorflow at first and run the demo.py under the directory: text-detection-ctpn-master, so the lib.networks.factory can be found.

**Comment by UpcominTerminator** [comment]
Hey even I am facing the same problem and I even tried you fix of running it from the root directory but I am getting new error now

Import error cannot import gpu_nms

**Comment by eragonruan** [comment]
@UpcominTerminator have you build the library?
