### ISSUE TITLE
ImportError: cannot import name 'bbox'

### ISSUE THREAD

**Issue by WeberLiu94** [eragonruan/text-detection-ctpn#133]
why i cannot import the bbox?

**Comment by eragonruan** [comment]
@WeberLiu94 you should build the library first

**Comment by JingangLang** [comment]
How to build the library on Windows 10 please? When I want to do it ,It shows:
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 26, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

**Comment by cks1999** [comment]
How to build the library  please?

**Comment by nitrlegend** [comment]
why dont you reply

**Comment by nitrlegend** [comment]
@eragonruan  reply plzz how to build a library

**Comment by eragonruan** [comment]
if you are using linux, follow readme to build the library. If you are using windows, search the issues, someone has build the library successfully on windows.
