### ISSUE TITLE
PyFPE_jbuf Error 

### ISSUE THREAD

**Issue by Navidaa** [eragonruan/text-detection-ctpn#172]
Hi, When Run the 

> python ./ctpn/demo.py

 I get this error:
Traceback (most recent call last):
  File "./ctpn/demo.py", line 8, in <module>
    from lib.networks.factory import get_network
  File "/home/navid/SharedFolder/text-detection-ctpn-master/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/home/navid/SharedFolder/text-detection-ctpn-master/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import train
  File "/home/navid/SharedFolder/text-detection-ctpn-master/lib/fast_rcnn/train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "/home/navid/SharedFolder/text-detection-ctpn-master/lib/roi_data_layer/__init__.py", line 1, in <module>
    from . import roidb
  File "/home/navid/SharedFolder/text-detection-ctpn-master/lib/roi_data_layer/roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "/home/navid/SharedFolder/text-detection-ctpn-master/lib/utils/__init__.py", line 5, in <module>
    from . import cython_nms
ImportError: /home/navid/SharedFolder/text-detection-ctpn-master/lib/utils/cython_nms.so: undefined symbol: PyFPE_jbuf

My command is: python ./ctpn/demo.py

**Comment by eragonruan** [comment]
https://github.com/smallcorgi/Faster-RCNN_TF/issues/149

**Comment by Liu98Fan** [comment]
have you fix it?I don't know how to fix it ,can you help me ? @Navidaa
