### ISSUE TITLE
When i run the demo.py ,there is an Error:Traceback (most recent call last):   File "/home/zhang/anaconda2/text-detection-ctpn-master/ctpn/demo.py", line 71, in <module>     cfg_from_file('ctpn/data/text.yml')   File "/home/zhang/anaconda2/text-detection-ctpn-master/lib/fast_rcnn/config.py", line 291, in cfg_from_file     with open(filename, 'r') as f: IOError: [Errno 2] No such file or directory: 'ctpn/data/text.yml'

### ISSUE THREAD

**Issue by zhengmingzhang** [eragonruan/text-detection-ctpn#179]

**Comment by Elsanna** [comment]
I have the same problem too. But the file is at the right direction.

**Comment by WrathofBhuvan11** [comment]
even i'm getting error
