### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by zhangxiaopang88** [eragonruan/text-detection-ctpn#190]
Hello, I am very glad that you can share your resources. I have done 3982 samples according to your steps, but I have made the following `mistakes.
`Traceback (most recent call last):
  File "./ctpn/train_net.py", line 20, in <module>
    roidb = get_training_roidb(imdb)
  File "/data/src/lab/zzy/text-detection-ctpn-master/lib/fast_rcnn/train.py", line 193, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/data/src/lab/zzy/text-detection-ctpn-master/lib/roi_data_layer/roidb.py", line 22, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
IndexError: list index out of range
``

**Comment by eragonruan** [comment]
try delete the cache in data/

**Comment by Fridayfairy** [comment]
I alse meet this issue,  which is caused by the conflict between new data with the pkl file
remove the voc_2007_trainval_gt_roidb.pkl
