### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ndarray'

### ISSUE THREAD

**Issue by louisly** [eragonruan/text-detection-ctpn#22]
when i try to train my own data, i faced this error：

Traceback (most recent call last):
  File "ctpn/train_net.py", line 41, in <module>
    restore=bool(int(1)))
  File "/data/resys/lvyi/exp/OCR_detect/text-detection-ctpn/lib/fast_rcnn/train.py", line 234, in train_net
    sw = SolverWrapper(sess, network, imdb, roidb, output_dir, logdir= log_dir, pretrained_model=pretrained_model)
  File "/data/resys/lvyi/exp/OCR_detect/text-detection-ctpn/lib/fast_rcnn/train.py", line 27, in __init__
    self.bbox_means, self.bbox_stds = rdl_roidb.add_bbox_regression_targets(roidb)
  File "/data/resys/lvyi/exp/OCR_detect/text-detection-ctpn/lib/roi_data_layer/roidb.py", line 58, in add_bbox_regression_targets
    _compute_targets(rois, max_overlaps, max_classes)
  File "/data/resys/lvyi/exp/OCR_detect/text-detection-ctpn/lib/roi_data_layer/roidb.py", line 136, in _compute_targets
    targets[ex_inds, 1:] = bbox_transform(ex_rois, gt_rois)
  File "/data/resys/lvyi/exp/OCR_detect/text-detection-ctpn/lib/fast_rcnn/bbox_transform.py", line 21, in bbox_transform
    assert np.min(ex_widths) > 0.1 and np.min(ex_heights) > 0.1, \
  File "/data/resys/var/python2.7.3/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2362, in amin
    if type(a) is not mu.ndarray:
AttributeError: 'module' object has no attribute 'ndarray'
Segmentation fault (core dumped)

**Comment by eragonruan** [comment]
which version of numpy are you using?
