### ISSUE TITLE
Training problem with new dataset and VOC2007 dataset

### ISSUE THREAD

**Issue by Anvarjon** [eragonruan/text-detection-ctpn#221]
I have successfully built text-detection-ctpn for CPU on my laptop. My environment python 2.7 and ubuntu 18.04.1. And then I downloaded ICDAR2017 database with its ground truth as well as prepared for training using split_label.py and ToVoc.py. There was not a problem. But when I tried to train network with my own prepared data there is a problem. Could anyone solve  this problem? Thanks in advance

Using config:
{'ANCHOR_SCALES': [16],
 'DATA_DIR': '/home/anvarjon/AI_Project/text-detection-ctpn-master/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'ctpn_end2end',
 'GPU_ID': 0,
 'IS_EXTRAPOLATING': True,
 'IS_MULTISCALE': False,
 'IS_RPN': True,
 'LOG_DIR': 'ctpn',
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/anvarjon/AI_Project/text-detection-ctpn-master/models/pascal_voc',
 'NCLASSES': 2,
 'NET_NAME': 'VGGnet',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'REGION_PROPOSAL': 'RPN',
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/anvarjon/AI_Project/text-detection-ctpn-master',
 'SUBCLS_NAME': 'voxel_exemplars',
 'TEST': {'BBOX_REG': True,
          'DETECT_MODE': 'H',
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 8,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 1000,
          'RPN_PRE_NMS_TOP_N': 12000,
          'SCALES': [600],
          'SVM': False,
          'checkpoints_path': 'checkpoints/'},
 'TRAIN': {'ASPECTS': [1],
           'ASPECT_GROUPING': True,
           'BATCH_SIZE': 300,
           'BBOX_INSIDE_WEIGHTS': [0, 1, 0, 1],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'DISPLAY': 10,
           'DONTCARE_AREA_INTERSECTION_HI': 0.5,
           'FG_FRACTION': 0.3,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'KERNEL_SIZE': 5,
           'LEARNING_RATE': 1e-05,
           'LOG_IMAGE_ITERS': 100,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'OHEM': False,
           'PRECLUDE_HARD_SAMPLES': True,
           'PROPOSAL_METHOD': 'gt',
           'RANDOM_DOWNSAMPLE': False,
           'RPN_BATCHSIZE': 300,
           'RPN_BBOX_INSIDE_WEIGHTS': [0, 1, 0, 1],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 8,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SCALES_BASE': [0.25, 0.5, 1.0, 2.0, 3.0],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 1000,
           'SNAPSHOT_PREFIX': 'VGGnet_fast_rcnn',
           'SOLVER': 'Adam',
           'STEPSIZE': 30000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False,
           'WEIGHT_DECAY': 0.0005,
           'max_steps': 50000,
           'restore': 0},
 'USE_GPU_NMS': False}
<bound method pascal_voc.default_roidb of <lib.datasets.pascal_voc.pascal_voc object at 0x7fe0994c6150>>
Loaded dataset `voc_2007_trainval` for training
Appending horizontally-flipped training examples...
Traceback (most recent call last):
  File "./ctpn/train_net.py", line 18, in <module>
    roidb = get_training_roidb(imdb)
  File "/home/anvarjon/AI_Project/text-detection-ctpn-master/lib/fast_rcnn/train.py", line 188, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/anvarjon/AI_Project/text-detection-ctpn-master/lib/datasets/imdb.py", line 86, in append_flipped_images
    widths = self._get_widths()
  File "/home/anvarjon/AI_Project/text-detection-ctpn-master/lib/datasets/imdb.py", line 82, in _get_widths
    for i in range(self.num_images)]
AttributeError: 'module' object has no attribute 'Image'

**Comment by Anvarjon** [comment]
I solve the problem by making some changes to lib\dataset\imdb.py file. The changes:
import PIL ---> from PIL import Image
PIL.Image..open(self.image_path_at(i)).size[0]  ---> Image..open(self.image_path_at(i)).size[0]

**Comment by AniketGurav** [comment]
Thanks @Anvarjon for solution

**Comment by hsonetta** [comment]
Hi , How did you annotate your data while preparing training data ?
