### ISSUE TITLE
我删除了 cache文件  但是依然报这个错

### ISSUE THREAD

**Issue by 425183525** [eragonruan/text-detection-ctpn#225]
Traceback (most recent call last):
  File "./ctpn/train_net.py", line 18, in <module>
    roidb = get_training_roidb(imdb)
  File "/raid/lhj/detectionText/text-detection-ctpn-untagged-48d74c6337a71b6b5f87/lib/fast_rcnn/train.py", line 188,
 in get_training_roidb    imdb.append_flipped_images()
  File "/raid/lhj/detectionText/text-detection-ctpn-untagged-48d74c6337a71b6b5f87/lib/datasets/imdb.py", line 88, in
 append_flipped_images    boxes = self.roidb[i]['boxes'].copy()
IndexError: list index out of range

**Comment by 425183525** [comment]
我删除  发下  再一次运行 发现又生成cache    谢谢你解答

**Comment by XXRRL** [comment]
删除以后，运行，肯定会从新生成cache啊
