### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by hcnhatnam** [eragonruan/text-detection-ctpn#271]
When I try to execute the main/train.py in new version code and receiving this error
/home/.../Documents/CTPNV2/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/home/.../Downloads/CTPNV2/arun.py", line 2, in <module>
    import main.train as train
  File "/home/.../Downloads/CTPNV2/main/train.py", line 11, in <module>
    from utils.dataset import data_provider as data_provider
  File "/home/.../Downloads/CTPNV2/utils/dataset/data_provider.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/home/.../Documents/CTPNV2/lib/python3.6/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/.../Documents/CTPNV2/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/.../Documents/CTPNV2/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/home/.../Documents/CTPNV2/lib/python3.6/site-packages/matplotlib/externals/six.py", line 90, in __get__
    result = self._resolve()
  File "/home/.../Documents/CTPNV2/lib/python3.6/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/home/.../Documents/CTPNV2/lib/python3.6/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'tkinter'

I using matplotlib==1.5.3.Can someone please help me with this ?

**Comment by hcnhatnam** [comment]
sudo apt-get install python3-tk
