### ISSUE TITLE
When running train.py code,the code be terminated with no error message

### ISSUE THREAD

**Issue by Allen-lz** [eragonruan/text-detection-ctpn#302]
Hello, author.
After I entered the command ‘python ./main/train.py’.then,without any error message, the ccode was stopped running . The terminal output the following:
================================================================
/home/cv_user/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
WARNING:tensorflow:Variable Conv/weights missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable Conv/biases missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable BiLSTM/bidirectional_rnn/fw/lstm_cell/kernel missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable BiLSTM/bidirectional_rnn/fw/lstm_cell/bias missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable BiLSTM/bidirectional_rnn/bw/lstm_cell/kernel missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable BiLSTM/bidirectional_rnn/bw/lstm_cell/bias missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable BiLSTM/weights missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable BiLSTM/biases missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable bbox_pred/weights missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable bbox_pred/biases missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable cls_pred/weights missing in checkpoint data/vgg_16.ckpt
WARNING:tensorflow:Variable cls_pred/biases missing in checkpoint data/vgg_16.ckpt
continue training from previous checkpoint 50000
================================================================
If you know how to solve it, please tell me the solution. Thank you!

**Comment by niddal-imam** [comment]
I have been trying to train the model, but the training process stops without any error message.

continue training from previous checkpoint 50000
WARNING:tensorflow:From /home/paperspace/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.

Any suggestion?

**Comment by yuzy007** [comment]
I have the same problem. How do you resolve it ?

**Comment by 18813055625** [comment]
有人解决这个问题吗

**Comment by Allen-lz** [comment]
tf.app.flags.DEFINE_boolean('restore', True, '')
set the 'True' to 'False',and you can run

**Comment by LeiGan0215** [comment]
> tf.app.flags.DEFINE_boolean('restore', True, '')
> set the 'True' to 'False',and you can run

Thanks,this solve my problem，thanks again

**Comment by QQ1696311291** [comment]
> > tf.app.flags.DEFINE_boolean('restore', True, '')
> > set the 'True' to 'False',and you can run
> 
> Thanks,this solve my problem，thanks again

An error appears after running
AttributeError: Can't pickle local object 'GeneratorEnqueuer.start.<locals>.data_generator_task'

(D:\Anaconda3) C:\Users\s\Desktop\ctpn3>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda3\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

What should I do

**Comment by cellphonef** [comment]
> https://github.com/eragonruan/text-detection-ctpn/issues/272

**Comment by cvnli** [comment]
> tf.app.flags.DEFINE_boolean('restore', True, '')
> set the 'True' to 'False',and you can run

it works

**Comment by GangaraniRajendran** [comment]
> > > tf.app.flags.DEFINE_boolean('restore', True, '')
> > > set the 'True' to 'False',and you can run
> > 
> > 
> > Thanks,this solve my problem，thanks again
> 
> An error appears after running
> AttributeError: Can't pickle local object 'GeneratorEnqueuer.start..data_generator_task'
> 
> (D:\Anaconda3) C:\Users\s\Desktop\ctpn3>Traceback (most recent call last):
> File "", line 1, in 
> File "D:\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
> exitcode = _main(fd)
> File "D:\Anaconda3\lib\multiprocessing\spawn.py", line 116, in _main
> self = pickle.load(from_parent)
> EOFError: Ran out of input
> 
> What should I do

Have resolved this EOF error? I am facing the same problem

**Comment by GangaraniRajendran** [comment]
> > > > tf.app.flags.DEFINE_boolean('restore', True, '')
> > > > set the 'True' to 'False',and you can run
> > > 
> > > 
> > > Thanks,this solve my problem，thanks again
> > 
> > 
> > An error appears after running
> > AttributeError: Can't pickle local object 'GeneratorEnqueuer.start..data_generator_task'
> > (D:\Anaconda3) C:\Users\s\Desktop\ctpn3>Traceback (most recent call last):
> > File "", line 1, in
> > File "D:\Anaconda3\lib\multiprocessing\spawn.py", line 106, in spawn_main
> > exitcode = _main(fd)
> > File "D:\Anaconda3\lib\multiprocessing\spawn.py", line 116, in _main
> > self = pickle.load(from_parent)
> > EOFError: Ran out of input
> > What should I do
> 
> Have resolved this EOF error? I am facing the same problem

Found the solution.... changing num_workers to 1 and multiprocessing to False solved the issue

**Comment by titan27149** [comment]
> multiprocessing

Can you be more specific? Where is this variable?3Q~
