### ISSUE TITLE
Can someone tell me how to change this?

### ISSUE THREAD

**Issue by QQ1696311291** [eragonruan/text-detection-ctpn#341]
The authors provide segmentation tags in the code input of a rectangular box of four points, that is, eight coordinates, but to provide the data set only the rectangular boxes inside the upper left and lower right 2 points, that is, four coordinates, so according to my understanding, I made a modified input coordinates of the code (I'm not sure is right, but I feel is right), run the code, and the results showed the following error, I don't know how to solve, could someone please help me to solve this problem?Here is the code I modified and the result:

  0%|          | 0/229 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:/Users/s/Desktop/ctpn3/utils/prepare/split_label.py", line 74, in <module>
    poly = orderConvex(poly)
  File "C:\Users\s\Desktop\ctpn3\utils\prepare\utils.py", line 17, in orderConvex
    points = np.array(points.exterior.coords)[:4]
AttributeError: 'LineString' object has no attribute 'exterior'

**Comment by QQ1696311291** [comment]
I tried to modify the code:

		for line in lines:
			splitted_line = line.strip().lower().split(',')
			for i in range(len(splitted_line)):
				x1 = float(splitted_line[0])
				x4 = x1
				y1 = float(splitted_line[1])
				y2 = y1
				x3 = float(splitted_line[2])
				x2 = x3
				y3 = float(splitted_line[3])
				y4 = y3

**Comment by qingqing625** [comment]
thank you
