### ISSUE TITLE
How to use resnet instead of vgg16

### ISSUE THREAD

**Issue by JXMss** [eragonruan/text-detection-ctpn#349]
> WARNING:tensorflow:From H:\MachineLearning\match\text-detection-ctpn-banjin-dev\text-detection-ctpn-banjin-dev\nets\resnet_v2.py:213: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
> Instructions for updating:
> keep_dims is deprecated, use keepdims instead
> Traceback (most recent call last):
>   File "./main/train.py", line 122, in <module>
>     tf.app.run()
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "./main/train.py", line 49, in main
>     bbox_pred, cls_pred, cls_prob = model.model(input_image)
>   File "H:\MachineLearning\match\text-detection-ctpn-banjin-dev\text-detection-ctpn-banjin-dev\nets\model_train.py", line 72, in model
>     rpn_conv = slim.conv2d(conv5_3, 512, 3)
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
>     return func(*args, **current_args)
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1154, in convolution2d
>     conv_dims=2)
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
>     return func(*args, **current_args)
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1020, in convolution
>     inputs = ops.convert_to_tensor(inputs)
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 998, in convert_to_tensor
>     as_ref=False)
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1094, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 961, in _autopacking_conversion_function
>     return _autopacking_helper(v, inferred_dtype, name or "packed")
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 923, in _autopacking_helper
>     constant_op.constant(elem, dtype=dtype, name=str(i)))
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 196, in constant
>     value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 436, in make_tensor_proto
>     _AssertCompatible(values, dtype)
>   File "D:\Anaconda\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 347, in _AssertCompatible
>     (dtype.name, repr(mismatch), type(mismatch).__name__))
> TypeError: Expected float32, got OrderedDict([('resnet_v2_50/conv1', <tf.Tensor 'model_0/resnet_v2_50/conv1/BiasAdd:0' shape=(?, ?, ?, 64) dtype=float32>), ('resnet_v2_50/block1/unit_1/bottleneck_v2/shortcut', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_1/bottleneck_v2/shortcut/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block1/unit_1/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_1/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 64) dtype=float32>), ('resnet_v2_50/block1/unit_1/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_1/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 64) dtype=float32>), ('resnet_v2_50/block1/unit_1/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_1/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block1/unit_1/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_1/bottleneck_v2/add:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block1/unit_2/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_2/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 64) dtype=float32>), ('resnet_v2_50/block1/unit_2/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_2/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 64) dtype=float32>), ('resnet_v2_50/block1/unit_2/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_2/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block1/unit_2/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_2/bottleneck_v2/add:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block1/unit_3/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_3/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 64) dtype=float32>), ('resnet_v2_50/block1/unit_3/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_3/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 64) dtype=float32>), ('resnet_v2_50/block1/unit_3/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_3/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block1/unit_3/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_3/bottleneck_v2/add:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block1', <tf.Tensor 'model_0/resnet_v2_50/block1/unit_3/bottleneck_v2/add:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block2/unit_1/bottleneck_v2/shortcut', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_1/bottleneck_v2/shortcut/BiasAdd:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2/unit_1/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_1/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 128) dtype=float32>), ('resnet_v2_50/block2/unit_1/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_1/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 128) dtype=float32>), ('resnet_v2_50/block2/unit_1/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_1/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2/unit_1/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_1/bottleneck_v2/add:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2/unit_2/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_2/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 128) dtype=float32>), ('resnet_v2_50/block2/unit_2/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_2/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 128) dtype=float32>), ('resnet_v2_50/block2/unit_2/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_2/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2/unit_2/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_2/bottleneck_v2/add:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2/unit_3/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_3/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 128) dtype=float32>), ('resnet_v2_50/block2/unit_3/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_3/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 128) dtype=float32>), ('resnet_v2_50/block2/unit_3/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_3/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2/unit_3/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_3/bottleneck_v2/add:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2/unit_4/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_4/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 128) dtype=float32>), ('resnet_v2_50/block2/unit_4/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_4/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 128) dtype=float32>), ('resnet_v2_50/block2/unit_4/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_4/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2/unit_4/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_4/bottleneck_v2/add:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block2', <tf.Tensor 'model_0/resnet_v2_50/block2/unit_4/bottleneck_v2/add:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block3/unit_1/bottleneck_v2/shortcut', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_1/bottleneck_v2/shortcut/BiasAdd:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_1/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_1/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_1/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_1/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_1/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_1/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_1/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_1/bottleneck_v2/add:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_2/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_2/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_2/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_2/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_2/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_2/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_2/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_2/bottleneck_v2/add:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_3/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_3/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_3/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_3/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_3/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_3/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_3/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_3/bottleneck_v2/add:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_4/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_4/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_4/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_4/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_4/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_4/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_4/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_4/bottleneck_v2/add:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_5/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_5/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_5/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_5/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_5/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_5/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_5/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_5/bottleneck_v2/add:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_6/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_6/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_6/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_6/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 256) dtype=float32>), ('resnet_v2_50/block3/unit_6/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_6/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3/unit_6/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_6/bottleneck_v2/add:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block3', <tf.Tensor 'model_0/resnet_v2_50/block3/unit_6/bottleneck_v2/add:0' shape=(?, ?, ?, 1024) dtype=float32>), ('resnet_v2_50/block4/unit_1/bottleneck_v2/shortcut', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_1/bottleneck_v2/shortcut/BiasAdd:0' shape=(?, ?, ?, 2048) dtype=float32>), ('resnet_v2_50/block4/unit_1/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_1/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block4/unit_1/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_1/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block4/unit_1/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_1/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 2048) dtype=float32>), ('resnet_v2_50/block4/unit_1/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_1/bottleneck_v2/add:0' shape=(?, ?, ?, 2048) dtype=float32>), ('resnet_v2_50/block4/unit_2/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_2/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block4/unit_2/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_2/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block4/unit_2/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_2/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 2048) dtype=float32>), ('resnet_v2_50/block4/unit_2/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_2/bottleneck_v2/add:0' shape=(?, ?, ?, 2048) dtype=float32>), ('resnet_v2_50/block4/unit_3/bottleneck_v2/conv1', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_3/bottleneck_v2/conv1/Relu:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block4/unit_3/bottleneck_v2/conv2', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_3/bottleneck_v2/conv2/Relu:0' shape=(?, ?, ?, 512) dtype=float32>), ('resnet_v2_50/block4/unit_3/bottleneck_v2/conv3', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_3/bottleneck_v2/conv3/BiasAdd:0' shape=(?, ?, ?, 2048) dtype=float32>), ('resnet_v2_50/block4/unit_3/bottleneck_v2', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_3/bottleneck_v2/add:0' shape=(?, ?, ?, 2048) dtype=float32>), ('resnet_v2_50/block4', <tf.Tensor 'model_0/resnet_v2_50/block4/unit_3/bottleneck_v2/add:0' shape=(?, ?, ?, 2048) dtype=float32>), ('global_pool', <tf.Tensor 'model_0/resnet_v2_50/pool5:0' shape=(?, 1, 1, 2048) dtype=float32>)]) of type 'OrderedDict' instead.

The screen shows these when I run the modified file

```
"train.py" line 22
tf.app.flags.DEFINE_string('pretrained_model_path', 'data/vgg_16.ckpt', '')
to
tf.app.flags.DEFINE_string('pretrained_model_path', 'data/resnet_v2_50.ckpt', '')
```

```
"model_train.py" line 5
from nets import vgg
to
from nets import resnet_v2, resnet_utils
```

```
line 68,69
with slim.arg_scope(vgg.vgg_arg_scope()):
conv5_3 = vgg.vgg_16(image)
to
with slim.arg_scope(resnet_utils.resnet_arg_scope()):
conv5_3 = resnet_v2.resnet_v2_50(image)
```

that's all i modified
i would appreciate it if you could help me.
@eragonruan

**Comment by luckydog5** [comment]
Same error, have u solved it?

**Comment by JXMss** [comment]
@luckydog5 nope :<

**Comment by luckydog5** [comment]
try this:
with slim.arg_scope(resnet_v1.resnet_arg_scope()):
        net , end_points = resnet_v1.resnet_v1_50(image, num_classes=None, is_training=False)
conv5_3 = end_points['resnet_v1_50/block3/unit_4/bottleneck_v1/conv2']


The network runs well but without convergence.

**Comment by JXMss** [comment]
thx a lot!!! @luckydog5 i'll try it :>
change some parameters may be effective
change to VGG19 is much easier than resnet and it works well but converges a little bit slower than VGG16(I hope you don't mind my rusty english.XDD)

**Comment by luckydog5** [comment]
@JXMss  How many steps have you trained before convergence with VGG-19.

In my case, the model seems will never be convergency.

**Comment by JXMss** [comment]
5k? im not sure.
up to 15k.
@luckydog5

**Comment by JXMss** [comment]
国人吗？ @luckydog5

**Comment by luckydog5** [comment]
@JXMss  😂😂😂😂， 真是尴尬。resnet50也没有问题，我之前是因为对训练图片进行了resize导致一直不收敛，去掉之后就好了。。

**Comment by JXMss** [comment]
woc 我是用的resnet v2
loss一塌糊涂 cross_entropy倒是稳步下降 见鬼了……
我看看再改改这个模块参数吧……（痛哭）
conv5_3 = end_points['resnet_v2_50/block4/unit_3/bottleneck_v2/conv2']

**Comment by JXMss** [comment]
@luckydog5 话说怎么确定这个模块参数呀 我只找到一个模块参数索引 但不知道选哪个

**Comment by JXMss** [comment]
恳请大佬指条明路

**Comment by luckydog5** [comment]
@JXMss  你直接print end_points ，我是参考vgg16选择resnet中层输出shape是（?,?,?,512)或者（？，？，？，256）都可以，反正就试着来吧。

**Comment by JXMss** [comment]
@luckydog5 感谢大佬 我再去试试

**Comment by aluckydog0716** [comment]
请问你是怎么解决  no module name ‘utils.bbox.bbox’的？方便 的话回复一下

**Comment by JXMss** [comment]
@aluckydog0716 没遇到过……抱歉 帮不上忙

**Comment by aluckydog0716** [comment]
有一个事问你一下，我在按照作者的步骤做预处理的时候，那个split_lable.py代码，中的DATA_FOLDER是放数据集的嘛？我什么我跑一下无事发生？

**Comment by aluckydog0716** [comment]
就是utils/prep/split_label.py

**Comment by maozezhong** [comment]
@luckydog5 请问用上resnet效果怎么样？

**Comment by maozezhong** [comment]
@luckydog5 resize不收敛指的是？  是resize到,600*800了吗？

**Comment by aluckydog0716** [comment]
@maozezhong    我没有尝试使用resnet，我用VGG16训练出来的效果也很理想

**Comment by bagpeng** [comment]
@JXMss 请问怎么将VGG替换成resnet

**Comment by JXMss** [comment]
@maozezhong res的效果并不好 综合效果不如VGG

**Comment by JXMss** [comment]
@maozezhong 不收敛指的是resnet不管怎么训练 loss都不收敛 发生这个问题的原因是conv5_3 = end_points['resnet_v2_50/block4/unit_3/bottleneck_v2/conv2']中括号内的参数设置的不对
至于参数应该填什么 给你一个网址 你对照着尝试吧……https://blog.csdn.net/qq_28424679/article/details/81013801

**Comment by JXMss** [comment]
@bagpeng 时间有点长了 我也不确定对不对 就是我这篇issue里 进行的前两个操作+ 第三个操作改成with slim.arg_scope(resnet_v1.resnet_arg_scope()):
net , end_points = resnet_v1.resnet_v1_50(image, num_classes=None, is_training=False)
conv5_3 = end_points['resnet_v1_50/block3/unit_4/bottleneck_v1/conv2']
当然 end_point里的参数需要你自己去找 上面这楼写了

不建议resnet 因为vgg综合效果更好

**Comment by byliut** [comment]
两位大佬，看你们讨论的激烈，小白问个问题。他这个第一条download the pre-trained model of VGG net and put it in data/vgg_16.ckpt. you can download it from tensorflow/models是什么意思啊？这个vgg_16.ckpt是个文件还是文件夹啊？他给的链接指向的是一个有很多文件的文件夹呀，这个要怎么操作啊。我是零基础小白，求大佬赐教

**Comment by byliut** [comment]
> @bagpeng 时间有点长了 我也不确定对不对 就是我这篇issue里 进行的前两个操作+ 第三个操作改成
> with slim.arg_scope(resnet_v1.resnet_arg_scope()):
> net , end_points = resnet_v1.resnet_v1_50(image, num_classes=None, is_training=False)
> conv5_3 = end_points['resnet_v1_50/block3/unit_4/bottleneck_v1/conv2']
> 当然 end_point里的参数需要你自己去找 上面这楼写了
> 
> 不建议resnet 因为vgg综合效果更好

两位大佬，看你们讨论的激烈，小白问个问题。他这个第一条download the pre-trained model of VGG net and put it in data/vgg_16.ckpt. you can download it from tensorflow/models是什么意思啊？这个vgg_16.ckpt是个文件还是文件夹啊？他给的链接指向的是一个有很多文件的文件夹呀，这个要怎么操作啊。我是零基础小白，求大佬赐教
