### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by hqh312** [eragonruan/text-detection-ctpn#372]
TypeError: 'module' object is not callable

         [[{{node model_0/anchor_target_layer/PyFunc}}]]
         [[{{node model_0/anchor_target_layer/PyFunc}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 118, in <module>
    tf.app.run()
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 97, in main
    input_im_info: data[2]})
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: 'module' object is not callable
Traceback (most recent call last):

  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/root/MyHqh/text_CTPN/Myutils/rpn_msr/anchor_target_layer.py", line 129, in anchor_target_layer
    overlaps = bbox_overlaps(np.ascontiguousarray(anchors, dtype=np.float),np.ascontiguousarray(gt_boxes, dtype=np.float))  # \u5047\u8bbeanchors\u6709x\u4e2a\uff0cgt_boxes\u6709y\u4e2a\uff0c\u8fd4\u56de\u7684\u662f\u4e00\u4e2a\uff08x,y\uff09\u7684\u6570\u7ec4

TypeError: 'module' object is not callable

         [[node model_0/anchor_target_layer/PyFunc (defined at /root/MyHqh/text_CTPN/hqh/netss/model_train.py:95) ]]
         [[node model_0/anchor_target_layer/PyFunc (defined at /root/MyHqh/text_CTPN/hqh/netss/model_train.py:95) ]]

**Comment by Xumingqian** [comment]
same questions，have you solved it ?

**Comment by ebinzacharias** [comment]
Any solution?

**Comment by MassKer-zjh** [comment]
https://github.com/0xcryptowang/text-detection-ctpn/blob/master/nets/model_train.py

**Comment by MassKer-zjh** [comment]
https://github.com/0xcryptowang/text-detection-ctpn/blob/master/nets/model_train.py
There is a model_train.py, I use it to solve this problem
