### ISSUE TITLE
ImportError: No module named 'utils.bbox.bbox'

### ISSUE THREAD

**Issue by 521alice** [eragonruan/text-detection-ctpn#378]
在Windows10 上部署，出现了这样的报错
Traceback (most recent call last):
  File "D:/text-detection-ctpn/main/demo.py", line 12, in <module>
    from nets import model_train as model
  File "D:\text-detection-ctpn\nets\model_train.py", line 5, in <module>
    from utils.rpn_msr.anchor_target_layer import anchor_target_layer as anchor_target_layer_py
  File "D:\text-detection-ctpn\utils\rpn_msr\anchor_target_layer.py", line 4, in <module>
    from utils.bbox.bbox import bbox_overlaps
ImportError: No module named 'utils.bbox.bbox'

**Comment by tt0829** [comment]
一样

**Comment by tt0829** [comment]
找到解决办法了吗

**Comment by 521alice** [comment]
> 找到解决办法了吗

我找到了另外的部署方式 地址是： [https://blog.csdn.net/yx123919804/article/details/84377026](url)

**Comment by mrxiaohe** [comment]
did you add `__init__.py` in the relevant folders? I added it to utils and bbox folders.

**Comment by AyushP123** [comment]
You have to build the project, go to utils/bbox and run make.sh. Its easier to run it in linux and I would recommend doing that.

**Comment by 1810325** [comment]
@mrxiaohe 请问这个问题你能教一下我吗，看了好久都没有解决

**Comment by yunzhi-wu** [comment]
"python setup.py build", then copy the generated .pyd files into bbox folder. It works for me.

**Comment by 1810325** [comment]
@yunzhi-wu 
![image](https://user-images.githubusercontent.com/47933430/66462872-8c443480-eaae-11e9-8be2-d3ee8b824549.png)whats wrong with me

**Comment by ldlbest** [comment]
> did you add __init__.py in the relevant folders? I added it to utils and bbox folders.
yes,but it did‘t soloved.

**Comment by ldlbest** [comment]
> generated .pyd

Please more details,thanks

**Comment by ldlbest** [comment]
> "python setup.py build", then copy the generated .pyd files into bbox folder. It works for me.
Do I need to write a setup.py by myself?

**Comment by SimeonKraev** [comment]
@ldlbest No, you don't need to write it yourself, its here --> text-detection-ctpn/utils/bbox/setup.py
You also might wanna try running everything with python 3.5

**Comment by dangvansam98** [comment]
text-detection-ctpn\utils\bbox> python setup.py build 
it make new "build" folder
then copy 2 file in "build\lib.win-amd64-3.6\" back to "text-detection-ctpn\utils\bbox\"

**Comment by KKDDD** [comment]
i have the same problem 
![image](https://user-images.githubusercontent.com/21326738/79315958-46bd6400-7f36-11ea-89a7-617b9e6cf73e.png)
![image](https://user-images.githubusercontent.com/21326738/79315976-4cb34500-7f36-11ea-9963-353069552c14.png)

**Comment by KKDDD** [comment]
> python

i have done this step，but still have errors

**Comment by KKDDD** [comment]
> text-detection-ctpn \ utils \ bbox> python setup.py构建
> 它以创建新的“ build”文件夹，
> 然后将“ build \ lib.win-amd64-3.6”中的2个文件复制回“ text-detection-ctpn \ utils \ bbox” ”

i have done this step，but still have errors

**Comment by dangvansam98** [comment]
You got that eror because no have folder “utils/rpn_msr”. You need to copy folder “rpn_msr” from repo to “utils” and try again

**Comment by gokudera17** [comment]
> 
> 
> text-detection-ctpn\utils\bbox> python setup.py build
> it make new "build" folder
> then copy 2 file in "build\lib.win-amd64-3.6" back to "text-detection-ctpn\utils\bbox"

it works!
