### ISSUE TITLE
I can process a photo, then I will see this question. What is the reason?

### ISSUE THREAD

**Issue by wanying321** [eragonruan/text-detection-ctpn#421]
Traceback (most recent call last):
  File "./main/demo.py", line 121, in <module>
    tf.app.run()
  File "/home/wy/anaconda2/envs/ctpn/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/wy/anaconda2/envs/ctpn/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/wy/anaconda2/envs/ctpn/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./main/demo.py", line 109, in main
    **img = cv2.resize(img, None, None, fx=1.0 / rh, fy=1.0 / rw, interpolation=cv2.INTER_LINEAR)
ZeroDivisionError: float division by zero**

**Comment by BarCodeReader** [comment]
just do your search among these 238 issues..someone already counter this problem.
use your brain instead of mouth to ask

**Comment by zhang-linrui** [comment]
It is because that function resize_img returns zero scale ratio back caused by py2.
The problem can be solved by modify line 51 in demo.py:
`return re_im, (new_h / img_size[0], new_w / img_size[1])`
as:
`return re_im, (1.0*new_h / img_size[0], 1.0*new_w / img_size[1])`
Good Luck
