### ISSUE TITLE
Error running demo 

### ISSUE THREAD

**Issue by sandeep-zeni** [eragonruan/text-detection-ctpn#428]
https://github.com/eragonruan/text-detection-ctpn/blob/0acfdeb48b3a741817a674a32ab4e4cb3c39cb99/main/demo.py#L51

$ python ./main/demo.py

data/demo/006.jpg
cost time: 1.47s
Traceback (most recent call last):
  File "./main/demo.py", line 121, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/Users/<username>/Library/Python/2.7/lib/python/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/< username>/Library/Python/2.7/lib/python/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./main/demo.py", line 109, in main
    img = cv2.resize(img, None, None, fx=1.0 / rh, fy=1.0 / rw, interpolation=cv2.INTER_LINEAR)
ZeroDivisionError: float division by zero

**Comment by sandeep-zeni** [comment]
Fixed using floating point division.

return re_im, ((1.0*new_h) / img_size[0], (1.0*new_w) / img_size[1])
