### ISSUE TITLE
run demo.py, an error occured!

### ISSUE THREAD

**Issue by hsyy673150343** [eragonruan/text-detection-ctpn#447]
Traceback (most recent call last):
  File "/home/hs/PycharmProjects/text-detection-ctpn/main/demo.py", line 12, in <module>
    from nets import model_train as model
  File "/home/hs/PycharmProjects/text-detection-ctpn/nets/model_train.py", line 2, in <module>
    from tensorflow.contrib import slim
ImportError: cannot import name 'slim'

**Comment by Mohamed209** [comment]
what is your tensorflow version ?
try use tensorflow==1.15 , i think it is the most stable and compatible version

**Comment by sevany** [comment]
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    from nets import model_train as model
ModuleNotFoundError: No module named 'nets'

**Comment by Mohamed209** [comment]
@sevany make sure you run the file demo from project root 
```
Python ./main/demo.py
```

**Comment by yujmo** [comment]
root@instance-oosc9xek:~/text-detection-ctpn# python2 ./main/demo.py 
Traceback (most recent call last):
  File "./main/demo.py", line 12, in <module>
    from nets import model_train as model
  File "/root/text-detection-ctpn/nets/model_train.py", line 5, in <module>
    from utils.rpn_msr.anchor_target_layer import anchor_target_layer as anchor_target_layer_py
ImportError: No module named utils.rpn_msr.anchor_target_layer
root@instance-oosc9xek:~/text-detection-ctpn#

**Comment by Mohamed209** [comment]
@yujmo 
nms and bbox utils are written in cython, hence you have to build the library first
have you built them
`cd utils/bbox
chmod +x make.sh
./make.sh`
