### ISSUE TITLE
ImportError: cannot import name 'bbox' from partially initialized module 'lib.utils' (most likely due to a circular import) (/home/barry/Github/chinese_ocr/ctpn/lib/utils/__init__.py)

### ISSUE THREAD

**Issue by Barry1915** [eragonruan/text-detection-ctpn#481]
Traceback (most recent call last):
  File "/home/barry/Github/chinese_ocr/demo.py", line 3, in <module>
    import ocr
  File "/home/barry/Github/chinese_ocr/ocr.py", line 10, in <module>
    from ctpn.text_detect import text_detect
  File "/home/barry/Github/chinese_ocr/ctpn/text_detect.py", line 6, in <module>
    from lib.utils.timer import Timer
  File "/home/barry/Github/chinese_ocr/ctpn/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/home/barry/Github/chinese_ocr/ctpn/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import train
  File "/home/barry/Github/chinese_ocr/ctpn/lib/fast_rcnn/train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "/home/barry/Github/chinese_ocr/ctpn/lib/roi_data_layer/__init__.py", line 1, in <module>
    from . import roidb
  File "/home/barry/Github/chinese_ocr/ctpn/lib/roi_data_layer/roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "/home/barry/Github/chinese_ocr/ctpn/lib/utils/__init__.py", line 4, in <module>
    from . import bbox
ImportError: cannot import name 'bbox' from partially initialized module 'lib.utils' (most likely due to a circular import) (/home/barry/Github/chinese_ocr/ctpn/lib/utils/__init__.py)

**Comment by Barry1915** [comment]
谁能帮帮我解决一下这个问题啊

**Comment by wxydaydayup** [comment]
在报错的地方上面加上这两行
import pyximport
pyximport.install()

**Comment by nissansz** [comment]
> import pyximport
> pyximport.install()

win10下也报这个错误。怎么解决？微信 nlanguage
