### ISSUE TITLE
training error( KeyError: 'max_overlaps')

### ISSUE THREAD

**Issue by shuihuadx** [eragonruan/text-detection-ctpn#91]
@eragonruan
Thanks for your share the code so much!!

I tried to train my model with 1000 images from [MLT](http://rrc.cvc.uab.es/?ch=8&com=downloads) (Because i want to see the results as soon as possible) followed the [README](https://github.com/eragonruan/text-detection-ctpn/blob/master/README.md),and the step of prepare data is all right(`python split_label.py` and `python ToVoc.py`executed successful),
but a got a error when i executed `python ./ctpn/train_net.py`,here is my error:

> Computing bounding-box regression targets...
Traceback (most recent call last):
  File "./ctpn/train_net.py", line 37, in <module>
    restore=bool(int(cfg.TRAIN.restore)))
  File "/home/gamepp/DX/text-detection-ctpn/lib/fast_rcnn/train.py", line 224, in train_net
    sw = SolverWrapper(sess, network, imdb, roidb, output_dir, logdir= log_dir, pretrained_model=pretrained_model)
  File "/home/gamepp/DX/text-detection-ctpn/lib/fast_rcnn/train.py", line 23, in __init__
    self.bbox_means, self.bbox_stds = rdl_roidb.add_bbox_regression_targets(roidb)
  File "/home/gamepp/DX/text-detection-ctpn/lib/roi_data_layer/roidb.py", line 51, in add_bbox_regression_targets
    max_overlaps = roidb[im_i]['max_overlaps']
KeyError: 'max_overlaps'

How can i deal with this error?

**Comment by shuihuadx** [comment]
I found the [solution](https://www.jianshu.com/p/e1e83648060e)!
Therefore, just delete the foler  `text-detection-ctpn/data/cache`!
