### ISSUE TITLE
libcudart.so.9.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hsddlz** [eragonruan/text-detection-ctpn#93]
Traceback (most recent call last):
  File "ctpn/demo.py", line 8, in <module>
    from lib.networks.factory import get_network
  File "/media/ming/d2/ocr/ocr_test/text-detection-ctpn-master/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "/media/ming/d2/ocr/ocr_test/text-detection-ctpn-master/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import train
  File "/media/ming/d2/ocr/ocr_test/text-detection-ctpn-master/lib/fast_rcnn/train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "/media/ming/d2/ocr/ocr_test/text-detection-ctpn-master/lib/roi_data_layer/__init__.py", line 1, in <module>
    from . import roidb
  File "/media/ming/d2/ocr/ocr_test/text-detection-ctpn-master/lib/roi_data_layer/roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "/media/ming/d2/ocr/ocr_test/text-detection-ctpn-master/lib/utils/__init__.py", line 6, in <module>
    from . import gpu_nms
ImportError: libcudart.so.9.1: cannot open shared object file: No such file or directory

my tf is 1.4 ,cuda is 9.0 .do I need to update to 9.1?  but 9.1 is still not stable in my computer`````what can I do

**Comment by eragonruan** [comment]
@hsddlz requires tensorflow 1.3， I am not sure if 1.4 works fine. Also, you may try create a soft link from libcudart.so.9.0 to libcudart.so.9.1
