### ISSUE TITLE
Can I train the model based on the files in "checkpoints" dir

### ISSUE THREAD

**Issue by FantDing** [eragonruan/text-detection-ctpn#95]
I copy the files in `checkpoints` dir into `./output/ctpn_end2end/voc_2007_trainval/` , but when I run `python3 ./ctpn/train_net.py`. I came cross errors. 
```python
Traceback (most recent call last):
  File "./ctpn/train_net.py", line 37, in <module>
    restore=bool(int(cfg.TRAIN.restore)))
  File "/home/fant/projects/python/text-detection-ctpn-master/lib/fast_rcnn/train.py", line 233, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "/home/fant/projects/python/text-detection-ctpn-master/lib/fast_rcnn/train.py", line 187, in train_model
    if last_snapshot_iter != iter:
UnboundLocalError: local variable 'iter' referenced before assignment
``` 
How can I resolve it

**Comment by FantDing** [comment]
I set `max_steps` in `text.yml` file to `60000`, then I can train normally. But loss is height and still shaked.

**Comment by cipri-tom** [comment]
it depends on what you train on. The model in `checkpoints` was trained as detailed in the readme. If you want to continue training with your own images, I can imagine these are very different, so the model will be "confused" and is normal to have a high loss.

If you want to train on a different set of images, I suggest you train from scratch. If it is too slow for you, I know of a couple of optimisations which I implemented in [my fork](https://github.com/cipri-tom/text-detection-ctpn)

**Comment by FantDing** [comment]
@cipri-tom Thank you! Now I use pretrained VGG16 model and all the parameters in VGG16 are not trained. That works well in terms of training speed. However, the final value of `total loss` is about 0.2 after 30K iters. That troubles me.

**Comment by cipri-tom** [comment]
@FantDing the loss tells you almost nothing, unless it is diverging. Remember it is an average of many things. Try to evaluate the model and see how it performs.

Next week I'll try to integrate an `eval` step during training, so you can pass a validation set and check the accuracy in TensorBoard.

**Comment by lxx1884896** [comment]
@FantDing ,Hi,I am sorry to bother you ,I want to know how do you make your training speed faster,just use  all the parameters in pretrained VGG16 ,or something else?I train the data with a 1080Ti ,but it's about 5~6s/iter,it's so slow. I have done the follow steps:

1.set use gpu nms : true in ctpn/text.yml and in lib/fast rcnn/config.py
2.cd lib/utils
  chmod +x make.sh
  ./make.sh    can you give me some advice,thank you
