### ISSUE TITLE
prepare my own dataset

### ISSUE THREAD

**Issue by FantDing** [eragonruan/text-detection-ctpn#98]
After I prepared the data as you said in `README.md`, I came cross such problem
```bash
Computing bounding-box regression targets...
Traceback (most recent call last):
  File "./ctpn/train_net.py", line 37, in <module>
    restore=bool(int(cfg.TRAIN.restore)))
  File "/home/fant/projects/python/text-detection-ctpn-test/lib/fast_rcnn/train.py", line 227, in train_net
    sw = SolverWrapper(sess, network, imdb, roidb, output_dir, logdir= log_dir, pretrained_model=pretrained_model)
  File "/home/fant/projects/python/text-detection-ctpn-test/lib/fast_rcnn/train.py", line 23, in __init__
    self.bbox_means, self.bbox_stds = rdl_roidb.add_bbox_regression_targets(roidb)
  File "/home/fant/projects/python/text-detection-ctpn-test/lib/roi_data_layer/roidb.py", line 51, in add_bbox_regression_targets
    max_overlaps = roidb[im_i]['max_overlaps']
KeyError: 'max_overlaps'
```
What is wrong? I can train the model with your prepared data.  Thank you!

**Comment by FantDing** [comment]
Removing `cache` dir in `./data` can solve
